/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 */

plugins {
    kotlin("jvm") version "1.6.10"
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    implementation("com.github.cesarferreira:kotlin-pluralizer:1.0.0")

    implementation("org.yaml:snakeyaml:1.29")
    implementation("com.github.beosign:snakeyaml-anno:1.3.0")
}